# Generated by Django 4.1.13 on 2024-10-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadedfile',
            table='uploaded_file',
        ),
    ]
