# Generated by Django 4.1.13 on 2024-10-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_alter_uploadedfile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadedfile',
            table=None,
        ),
    ]
